### ISSUE TITLE
[Enhancement] Update to AUTOMATIC1111 Upstream Will be this Friday

### ISSUE THREAD

**Issue by Interpause** [Interpause/auto-sd-krita#15]
Looking at the upstream commits, it is quite significant, and some of the internal APIs the backend server relies on was modified. As such, I will be putting off upstream merges till Friday to ensure the update goes smoothly.

Of course, Pull Requests that have been tested will be accepted.

**Comment by kiron111** [comment]
it's great to see your endeavour, thankyou for your hard work
I longed for a krita and webui comblined sd version, and just found your video on youtube today!!

Excellent work!!!

**Comment by aniketgore** [comment]
Will check this on Saturday. Thanks for your efforts.
