### ISSUE TITLE
Broken since today

### ISSUE THREAD

**Issue by ethanfel** [Interpause/auto-sd-krita#20]
using the plugin doesn't work anymore.

only a white layer or nothing is generated. I've made a clean install of everything to be sure.

**Comment by ethanfel** [comment]
with a checkout on  35ad11deffc9dc34d9c8025650d29901598a82fd it's working again

**Comment by lambschopping** [comment]
Yes, I'm also having problems with this. The checkout fixed it, but seems to roll back a lot of features in the webgui.

**Comment by danilw** [comment]
Same, just downloaded, image generated and saved in output but not downloaded back to Krita.
Will check fix above latter.

**Comment by Interpause** [comment]
Wait a while

**Comment by Interpause** [comment]
I can't reproduce the issue on my Linux machine. I cannot test on my Windows machine until I get home on Saturday.

**Comment by Interpause** [comment]
Issue has been reproduced; seems to occur only on fresh document. Occurs regardless of whether there is a selected area or nothing is selected. No idea why it breaks specifically for a fresh document... have to add that to my test checklist...

Actually I got a hypothesis already.

**Comment by danilw** [comment]
> I can't reproduce the issue on my Linux machine.

I setup this Krita plugin on top of exist AUTOMATIC1111/stable-diffusion-webui 
Also on Linux.

In my case - I see generated output in output directory, even with selected input(img2img), but loading back to Krita not happening.

> seems to occur only on fresh document.
I also thought about it, and tried on "create new"(not selecting anything), same but selecting full size (515x512), and opening exist image in Krita and editing it with text2img or img2img - every time result not uploaded back to Krita.

**Comment by Interpause** [comment]
This is the culprit: https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/8ec44fd8799ee236c99a9999c2343103dc4cd67b

**Comment by Interpause** [comment]
Sorry, I will fix it now

**Comment by Interpause** [comment]
BTW, it will work if the batch size is larger than 1 :p

**Comment by Interpause** [comment]
Its fixed: https://github.com/Interpause/auto-sd-krita/commit/5dae4261d9576b3be7648451a810fbf1f968be4f

Sorry for taking so long to notice, but personally I blame Github for somehow failing to notify me of this issue.

I probably should look into writing automated tests...

**Comment by danilw** [comment]
> Its fixed:

I can confirm it works now.
Thanks!

**Comment by ethanfel** [comment]
> Its fixed: [5dae426](https://github.com/Interpause/auto-sd-krita/commit/5dae4261d9576b3be7648451a810fbf1f968be4f)
> 
> Please follow https://github.com/Interpause/auto-sd-krita/wiki/Install-Guide#updating to update.
> 
> Sorry for taking so long to notice, but personally I blame Github for somehow failing to notify me of this issue.
> 
> I probably should look into writing automated tests...

thanks for the fix !
