### ISSUE TITLE
Assertion Error: Backend Error, check terminal when using selection and img2img

### ISSUE THREAD

**Issue by bnelsey** [Interpause/auto-sd-krita#23]
**Describe the bug**
these work:
- txt2img
- txt2img with a selection / feathered selection
- img2img

this does not work:
- img2img with a selection / feathered selection

**To Reproduce**
1. Make a selection in the image
2. Go to img2img tab
3. click [start img2img]
4. see errors in both krita and the terminal

**Expected behavior**
no error message appears

**Screenshots**
[Video of the problem](https://youtu.be/dC3Fv5N0-u8)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
Inpainting worked twice, but has never worked after that
The weird part is the error happens after stable diffusion is done rendering an image and sends the result back to Krita
I don't use inpainting, but I figured you want to know that info as well since it might be related to my main issue.

**Comment by bnelsey** [comment]
update: after looking at the error message in the video I took, I noticed the error happened right after the terminal said something about downloading the LDSR upscaler model
So I disabled the LDSR upscaler and feathered selections with img2img now work perfectly
This might be useful for anyone else with a similar problem

**Comment by Interpause** [comment]
For more information, AUTOMATIC1111's code will automatically download missing models.  It might appear as if its hanging during the process unfortunately.
