### ISSUE TITLE
When wrong IP/backend URL - Krita freeze

### ISSUE THREAD

**Issue by danilw** [Interpause/auto-sd-krita#25]
**Describe the bug** **To Reproduce**:
Just try to edit **Backend URL** in UI and type anything "wrong"

I was editing, and as usual pressed "delete button" to write address and had this `http://1:8000` - **Krita froze**
Restarting Krita - froze on "startup".

Writing any wrong address there leads to this freeze, example `http://8.8.8.8:8000`

**Screenshots**
![image](https://user-images.githubusercontent.com/24825887/196754227-283f948f-335d-412c-a07c-413139319a7f.png)

**Desktop:**
Linux version of Krita

**Fix** if someone else got this:
edit file `~/.config/krita/krita_diff_plugin.ini`
set `base_url=http://127.0.0.1:8000`

**Comment by Interpause** [comment]
Now it should give a warning in the status bar instead
