### ISSUE TITLE
ValueError: remove: path too long for Windows

### ISSUE THREAD

**Issue by PTFish8** [Interpause/auto-sd-krita#30]
this is screenshot:
![image](https://user-images.githubusercontent.com/72650071/197261761-959f7601-e221-42b6-95d7-6204bf616bcf.png)

this is content:

ValueError
Python 3.8.1: C:\Program Files\Krita (x64)\bin\krita.exe
Sat Oct 22 02:10:09 2022

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\Users\Name\AppData\Roaming\krita\pykrita\krita_diff\script.py in cb()
  262             self.update_selection()
  263             self.adjust_selection()
  264             self.apply_img2img(mode=0)
  265             self.create_mask_layer_workaround()
  266             self.set_status(STATE_IMG2IMG)
self = <krita_diff.script.Script object>
self.apply_img2img = <bound method Script.apply_img2img of <krita_diff.script.Script object>>
mode undefined

 C:\Users\Name\AppData\Roaming\krita\pykrita\krita_diff\script.py in apply_img2img(self=<krita_diff.script.Script object>, mode=0)
  207             self.clear_temp_images([path, mask_path, *outputs])
  208         else:
  209             self.clear_temp_images([path, *outputs])
  210         self.doc.refreshProjection()
  211 
self = <krita_diff.script.Script object>
self.clear_temp_images = <bound method Script.clear_temp_images of <krita_diff.script.Script object>>
path = r'C:\Program My\auto-sd-krita-master\outputs\krita-in\1666375779.png'
outputs = ['iVBORw0KGgoAAAANSUhEUgAAAgAAAAMACAIAAADdbUgZAAEA...zWIYOQwm3LGSTWW8MvPx/Ad8GIip1S60uAAAAAElFTkSuQmCC', 'iVBORw0KGgoAAAANSUhEUgAAAgAAAAMACAIAAADdbUgZAAEA...J0lkKeQ7G2oXcwSLA6f8HvbGvOrOZ5MEAAAAASUVORK5CYII=']

 C:\Users\Name\AppData\Roaming\krita\pykrita\krita_diff\script.py in clear_temp_images(self=<krita_diff.script.Script object>, files=[r'C:\Program My\auto-sd-krita-master\outputs\krita-in\1666375779.png', 'iVBORw0KGgoAAAANSUhEUgAAAgAAAAMACAIAAADdbUgZAAEA...zWIYOQwm3LGSTWW8MvPx/Ad8GIip1S60uAAAAAElFTkSuQmCC', 'iVBORw0KGgoAAAANSUhEUgAAAgAAAAMACAIAAADdbUgZAAEA...J0lkKeQ7G2oXcwSLA6f8HvbGvOrOZ5MEAAAAASUVORK5CYII='])
  239         if self.cfg("delete_temp_files", bool):
  240             for file in files:
  241                 os.remove(file)
  242 
  243     # Actions
global os = <module 'os' from 'C:\\Program Files\\Krita (x64)\\python\\python38.zip\\os.pyc'>
os.remove = <built-in function remove>
file = 'iVBORw0KGgoAAAANSUhEUgAAAgAAAAMACAIAAADdbUgZAAEA...zWIYOQwm3LGSTWW8MvPx/Ad8GIip1S60uAAAAAElFTkSuQmCC'
ValueError: remove: path too long for Windows
    __cause__ = None
    __class__ = <class 'ValueError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of ValueError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of ValueError object>
    __doc__ = 'Inappropriate argument value (of correct type).'
    __eq__ = <method-wrapper '__eq__' of ValueError object>
    __format__ = <built-in method __format__ of ValueError object>
    __ge__ = <method-wrapper '__ge__' of ValueError object>
    __getattribute__ = <method-wrapper '__getattribute__' of ValueError object>
    __gt__ = <method-wrapper '__gt__' of ValueError object>
    __hash__ = <method-wrapper '__hash__' of ValueError object>
    __init__ = <method-wrapper '__init__' of ValueError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of ValueError object>
    __lt__ = <method-wrapper '__lt__' of ValueError object>
    __ne__ = <method-wrapper '__ne__' of ValueError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of ValueError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of ValueError object>
    __repr__ = <method-wrapper '__repr__' of ValueError object>
    __setattr__ = <method-wrapper '__setattr__' of ValueError object>
    __setstate__ = <built-in method __setstate__ of ValueError object>
    __sizeof__ = <built-in method __sizeof__ of ValueError object>
    __str__ = <method-wrapper '__str__' of ValueError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ('remove: path too long for Windows',)
    with_traceback = <built-in method with_traceback of ValueError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\Users\Name\AppData\Roaming\krita\pykrita\krita_diff\script.py", line 264, in cb
    self.apply_img2img(mode=0)
  File "C:\Users\Name\AppData\Roaming\krita\pykrita\krita_diff\script.py", line 209, in apply_img2img
    self.clear_temp_images([path, *outputs])
  File "C:\Users\Name\AppData\Roaming\krita\pykrita\krita_diff\script.py", line 241, in clear_temp_images
    os.remove(file)
ValueError: remove: path too long for Windows

**Comment by PTFish8** [comment]
Error is prompted before the picture returns

**Comment by zvit** [comment]
I am getting the same error. The images are being generated in \auto-sd-krita\outputs\txt2img-images but I get the popup error and no image in the software.

**Comment by Interpause** [comment]
I missed something out while converting from sending file paths to the actual images itself. For now, disabling `automatically delete debug files` under the config tab will work. I will later be changing it to instead not save input/output images by default instead of saving it then clearing it later.
