### ISSUE TITLE
Possible freeze during image transfer using remote backend

### ISSUE THREAD

**Issue by Interpause** [Interpause/auto-sd-krita#31]
See: https://github.com/Interpause/auto-sd-krita/issues/24#issuecomment-1287142742

Possible freeze during image transfer in http request. Need to test if this is due to latency/connection issues when using a remote backend, or if it can happen for local backend as well.

Given that image generation can take an unspecified amount of time, fixing this likely means figuring out async/background threads in pyQt. One solution is to use the eta/status updates provided by upstream as a sort of keep alive mechanism to cancel the request.

**Comment by danilw** [comment]
> Need to test

I had this freeze just few times, and I do not have correct way to reproduce... happening randomly.
Sorry can not help on this one :(

**Comment by Interpause** [comment]
The freeze can happen locally.

**Comment by Interpause** [comment]
The freeze appears to be somewhat rare locally. However, sending 64 images at once (locally) didn't crash. It either means it isn't a network issue, or the network issue isn't due to the size of the image payload. It could also be I haven't tried sufficiently many images (or poor enough connection i.e. remote backend).

**Comment by danilw** [comment]
on remote backend (Colab) it also hapening very rare, I had whole sessions for about 1 hour time long with no problems at all

this is not very "important and serious problem" as I see it, for end user enough is just "save everything" before pressing Start in SD plugin 
(and fix to it may be way too overcomplicated, like adding exceptions and timers for every remote api call on client and server...)

**Comment by Interpause** [comment]
This should not occur anymore now that networking is threaded. Instead, it should either result in a network error or outright crash (#33).
