### ISSUE TITLE
Request to add the "Connect to Server Side On/Off" button. Users can choose whether to connect to the backend.

### ISSUE THREAD

**Issue by PTFish8** [Interpause/auto-sd-krita#35]
When I am painting, the back end is not opened. The plug-in will constantly try to connect to the back end. Every time I try to connect to the back end, the software will get stuck.
I hope you can add an "on/off button" or other functions to avoid software stuttering.

**Comment by PTFish8** [comment]
English is not my native language. I hope my description is not ambiguous.

**Comment by danilw** [comment]
I agree with this, working with Krita little bit annoying when plugin freeze it every few sec for few frames, and not used

**Comment by Interpause** [comment]
its not done yet, but you can try a branch where i have been trying to make everything async

**Comment by PTFish8** [comment]
> 它还没有完成，但你可以尝试一个分支，我一直在尝试使一切都异步

I see Thank you
