### ISSUE TITLE
Inpaint Masked content - fill option missing?

### ISSUE THREAD

**Issue by danilw** [Interpause/auto-sd-krita#36]
Sorry if I missing something in UI, but I dont see this option/alternative. Or I dont understand how it works if it exist.

**Is your feature request related to a problem? Please describe.**
Current SD Pluding dont have 
![image](https://user-images.githubusercontent.com/24825887/197399237-1888a8bd-c563-42e3-a56c-b4cea2ed1205.png)

this option, from Inpaint WebUI interface

current SD interface has only 4 options, with no "fill"
![image](https://user-images.githubusercontent.com/24825887/197399309-c151540a-53a8-434b-9804-10834ca3d4c2.png)

**Comment by Interpause** [comment]
I renamed the `fill` option to `blur` as I thought that was a clearer description of what it did based on this picture from AUTO's wiki:

![image](https://user-images.githubusercontent.com/42513874/197430393-a74f1142-9ca6-49c0-a837-7185e8fdf0bf.png)
