### ISSUE TITLE
krita freezing on splash screen

### ISSUE THREAD

**Issue by a7medee** [Interpause/auto-sd-krita#47]
after installing the plugin ,it worked well but after a couple restarts of krita it freezes at splash screen
It only starts after Removing the plugin files 

edit : solved by removing %APPDATA%\krita\krita_diff_plugin.ini
 - OS: [windows 10&11]

**Comment by Interpause** [comment]
Likely some sort of settings corruption. Interesting

**Comment by Interpause** [comment]
Is anyone else facing this? If not, I will just add deleting the settings file to the troubleshooting steps.
