### ISSUE TITLE
Details how to inpaint?

### ISSUE THREAD

**Issue by Abul22** [Interpause/auto-sd-krita#50]
Hi, I'm having a bit of trouble with this and seemingly getting diff results when doing some trial and error.

1: create img with txt2img
2: erase region of  img I want SD to inpaint?
*3: select the img layer and press inpaint. ... just gives me a new inpaint 1 layer... that is all white.

or

1: create img with txt2img
2: erase region of  transparency mask of the img I want SD to inpaint?
*3: select the img layer and press inpaint. ... just gives me a new  inpaint 1 layer... that is all white.

or
1: create img with txt2img
2: erase region of  transparency mask of the img I want SD to inpaint?
*3: select the transparency layer and press inpaint. ... Crashes Krita

Advice on what I might be doing wrong here would be appreciated! 

Cheers

**Comment by Interpause** [comment]
Watch the demo video: https://youtu.be/nP8MuRwcDN8
