### ISSUE TITLE
is inpaint broken? and this plugin still supported?

### ISSUE THREAD

**Issue by danilw** [Interpause/auto-sd-krita#53]
![image](https://user-images.githubusercontent.com/24825887/199559586-0ed744b6-8b5b-46b8-b519-4c69f0c1034a.png)

This is result of inpaint in Krita, on "this" latest(just launched and updated) plugin version.

**On server image is correct**:
![00001-1582881571-dress with legs](https://user-images.githubusercontent.com/24825887/199560373-99abdcaa-b800-4db7-9cfa-c0b01f0e37b7.png)

This happening only on image transfer, because server image is okey.
Only in inpaint, img2img is fine.
Happening when backend on "remote" and "localhost", I think this is not about internet speed.

**Is this plugin still supported?** Or you just switch on https://github.com/Interpause/auto-sd-paint-ext?

**Comment by Interpause** [comment]
Yes, I will be switching.

But this is a weird bug. What was your selection region & inpaint layer?

**Comment by danilw** [comment]
> But this is a weird bug. What was your selection region & inpaint layer?

I was making https://github.com/Interpause/auto-sd-krita/issues/32 and was not sure is it "my encryption bug" or this plugin and maybe it was updated, had no internet for few days, and was sitting on old version. Today checked last version - it still there.

Selection look like this: (this is not from first post selection, but result same)
![2](https://user-images.githubusercontent.com/24825887/199643271-9e88f837-58e8-42ca-81bb-776ccb6be6d7.png)

`img size: 524x327 -> 512x320, aspect ratio: 1.60 -> 1.60, -0.15% change` 

Only in inpaint, when on "localhost" it has - "broken cuts as lines", but when from Colab - cuts look like dota, noise with transparent dots everywhere.

I think if it "internet problem" or Async broke somehow - then it should happen in img2img also, but img2img always fine, I tested many times today.

**Comment by Interpause** [comment]
Under `defaults.py` in `krita_server`, there is a option `THREADED`. Set it to false to disable async. You also already tried with your encryption off right?

Send me the link to your fork, I'll see if I can reproduce the issue & figure out what is going on.

**Comment by danilw** [comment]
> You also already tried with your encryption off right?

yes - I tried with and without encryption (on clean clone of this your repository, because obviously I thought it my bug).

I have not updated Krita for 2 weeks so it same version for all this time. 

Maybe it somehow related to Linux version of Python, because server I running on localhost is on Linux, and same with Colab - there Linux.

Il post more detailed report today.

**Comment by danilw** [comment]
> Under `defaults.py` in `krita_server`, there is a option `THREADED`

it was in krita-client, and set it to False does not change anything

**but since you not support this plugin anymore - il just close this issue**

**Comment by Interpause** [comment]
I see, its fine. Do let me know if you encounter the issue in the new version because I have yet to encounter it.
