### ISSUE TITLE
unable to use erase on mask layer for inpaint

### ISSUE THREAD

**Issue by sould3mon** [Interpause/auto-sd-krita#9]
whatever white has touched when drawing a mask stay's as a mask even after erasing.

to reproduce:
create mask layer
use white to create mask
remove some of white (with eraser)

https://imgur.com/a/EYEA8H0
hope this is clear (used black baground to show instead of origional image) 

run inpaint 
everything that white has touched is rendered

**Comment by Interpause** [comment]
Oh yeah, I ran into that too but forgot about it :p
